### ISSUE TITLE
[BUG] 'runway tfenv install' broken

### ISSUE THREAD

**Issue by pataraco** [onicagroup/runway#1385]
### Bug Description

Hello,

This started happening yesterday Apr 13, 2022

We've tried all sort of combinations of runway/terraform/python versions and cannot seem to make this work anymore.

This is affect our CI/CD pipeline which can no longer install the version of terraform specified in the runway.yaml file because runway, i believe, is using runway tfenv to install the desired version of terraform

Any help would be greatly appreciated. Until then i'll be creating my own "wrapper" to install the desired versions of terraform myself into the directory runway is looking for $HOME/.tfenv/versions

Thanks!

```

devops/tfetest|~/repos/innovyze/devops-terraform
😄-bash-⌲ runway tfenv install 1.0.0
Traceback (most recent call last):
  File "/Users/patrick.raco/.local/bin/runway", line 8, in <module>
    sys.exit(cli())
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/main.py", line 33, in invoke
    return super().invoke(ctx)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/commands/_tfenv/_install.py", line 31, in install
    "terraform path: %s", TFEnvManager().install(version_requested=version)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 348, in install
    if not self.version:
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/backports/cached_property/__init__.py", line 80, in __get__
    val = self.func(instance)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 276, in version
    for i in get_available_tf_versions(include_prerelease_versions)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 118, in get_available_tf_versions
    reverse=True,
  File "/Users/patrick.raco/.pyenv/versions/3.7.12/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/patrick.raco/.pyenv/versions/3.7.12/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'```

### Expected Behavior

1. run: `runway tfenv install VERSION`
2. expect specified terraform version to be installed


### Steps To Reproduce

1. install `runway`: `pip install runway [--user]`
2. make sure desired version of terraform is not installed with: `runway tfenv list`
3. try to install it: `runway tfenv install --version`

### Runway version

- 1.18.1
- 1.18.3
- 2.6.1

### Installation Type

pypi (pip, pipenv, poetry, etc)

### OS / Environment

- macos
- linux

### Anything else?

- seems to happen if/when the desired version of terraform is NOT installed
- Did notice these diffs in the installed python packages between a successful and failed run:

![image](https://user-images.githubusercontent.com/3203156/163601117-349be257-6cfc-4f1b-8b97-82237ed6bc91.png)

**Comment by sagargulabani** [comment]
Hi we are also running into this issue, all our pipelines have started breaking. How do we reolve this.

**Comment by pataraco** [comment]
@sagargulabani as a workaround, i wrote something to install the required versions of terraform into the directory ($HOME/.tfenv/versions) that `runway` checks if it needs to install them itself using `runway tfenv` so it will be happy and just do the planning/deploying.

**Comment by pataraco** [comment]
in case a solution isn't found soon, hope these will help someone else:

```
#!/bin/bash
#
# purpose: install required terraform versions listed in .terraform-version
#

# enable bash debugging if set on the pipeline
if grep -Fiwq "true" <<< "$SYSTEM_DEBUG"; then set -x; fi

# globals
DEVOPS_SCRIPTS=$DEVOPS_ADO_SCRIPTS
TERRAFORM_VERSION_FILE=".terraform-version"

# loop through list of required terraform versions and install them
if [[ -f "$TERRAFORM_VERSION_FILE" ]]; then
  # shellcheck disable=SC2013
  for terraform_version in $(cat $TERRAFORM_VERSION_FILE); do
    echo "Installing Terraform version ($terraform_version) found in: $TERRAFORM_VERSION_FILE"
    "$DEVOPS_SCRIPTS/install-terraform.sh" "$terraform_version"
  done
else
  echo "The Terraform version file NOT found: $TERRAFORM_VERSION_FILE"
  echo "Cannot install Terraform versions needed in runway.yaml"
  exit 1
fi
```

```
#!/bin/bash
#
# purpose: install terraform version
#
# description: simple script to install a specific terraform version
# 
# note: the versions of terraform are installed into the
#       directory that runway is looking for so that
#       runway does not try to install it itself using `runway tfenv`
#       which is currently broken as of (13-APR-2022)
#

# enable bash debugging if set on the pipeline
if grep -Fiwq "true" <<< "$SYSTEM_DEBUG"; then set -x; fi

THIS_SCRIPT=$(basename "$0")
TF_ENV_DIR="$HOME/.tfenv/versions"  # this is where runway is looking
# create the directory if it doesn't exist
[[ ! -d $TF_ENV_DIR ]] && mkdir -p $TF_ENV_DIR
TF_RELEASES_URL="https://releases.hashicorp.com"
USAGE=\
"usage:
  $THIS_SCRIPT VERSION      install specified terraform version
  $THIS_SCRIPT -s | --show  show installed terraform versions
  $THIS_SCRIPT -h | --help  disploy this help/usage"

# get the version to install
tf_version_desired=$1

function show_installed_versions {
  # shellcheck disable=SC2086
  if ls -d $TF_ENV_DIR/* &> /dev/null; then
    echo "these are the installed versions:"
    ls "$TF_ENV_DIR"
  else
    echo "there are no installed versions"
  fi
}

# command: help - show help
if [[ "$tf_version_desired" == "-h" ]] || [[ "$tf_version_desired" == "--help" ]]; then
  echo "this function helps to install a specific terraform version"
  echo "$USAGE"
# command: show - show terraform versions installed/available
elif [[ "$tf_version_desired" == "-s" ]] || [[ "$tf_version_desired" == "--show" ]]; then
  show_installed_versions
# command: "install" (default) - install the specified terraform version
elif [[ -n "$tf_version_desired" ]]; then
  if [[ -x "$TF_ENV_DIR/$tf_version_desired/terraform" ]]; then
    echo "desired version ($tf_version_desired) already installed in '$TF_ENV_DIR'"
  else
    echo "did not find desired version ($tf_version_desired) in '$TF_ENV_DIR'"
    show_installed_versions
    echo "going to attempt to install it"
    host_arch=$(uname -m)
    case $host_arch in
      x86_64) arch=amd64;;
      arm64) arch=arm64;;
      *) arch=unknown;;
    esac
    host_os=$(uname -s)
    case $host_os in
      Darwin) os=darwin;;
      Linux) os=linux;;
      *) os=unknown;;
    esac
    if [[ "$arch" == "unknown" ]] && [[ "$os" == "unknown" ]]; then
      echo "cannot determine correct terraform binary to download for (Arch: $host_arch, O.S.: $host_os)"
      exit
    fi
    tf_version_zip_name="terraform_${tf_version_desired}_${os}_${arch}.zip"
    tf_version_url="${TF_RELEASES_URL}/terraform/${tf_version_desired}/${tf_version_zip_name}"
    if curl -s -f -o "/tmp/${tf_version_zip_name}" "${tf_version_url}"; then
      [[ ! -d "$TF_ENV_DIR" ]] && mkdir "$TF_ENV_DIR"
      unzip "/tmp/${tf_version_zip_name}" -d "$TF_ENV_DIR/$tf_version_desired"
      echo "successfully installed desired version ($tf_version_desired) in '$TF_ENV_DIR'"
      show_installed_versions
    else
      tf_available_versions="$(curl -s "${TF_RELEASES_URL}/terraform/" | grep -oE 'terraform_\d+\.\d+.\d+' | sort -uV | sed 's/^terraform_//' | tr '\n' ',' | sed 's/,/, /g')"
      echo "cannot find desired version ($tf_version_desired) at '$TF_RELEASES_URL'"
      echo "these are the available versions:"
      echo "   $tf_available_versions"
      exit
     fi
  fi
# command: none - show usage
else
  echo "error: incorrect usage"
  echo "$USAGE"
fi
```

**Comment by pataraco** [comment]
Hey @ITProKyle !
how's it going?
Any clue?

**Comment by ITProKyle** [comment]
From your screenshot you are using runway 1.16.0 which is quite old. There have been many improvement and bug fixes since then. I would recommend trying the latest version.

FYI I no longer work for the company that owns this project and they did not allow me to remain a maintainer. For further support I would recommend reach out to Onica/Rackspace.

**Comment by pataraco** [comment]
Hey @ITProKyle ,
yeah, i've already heard... i was wondering why you were still able to be @mentioned here. so, since you were, i assumed you still had contribution rights, LOL!

i tried a bunch of different versions and couldn't it to work.
but today in another repo, that previously did NOT work, is now working.
and haven't found the differences between the 2 repos now. 🤷‍♂️

thanks for responding - hope you're doing well!

**Comment by pataraco** [comment]
some more info:

```
devops/tfetest|~/repos/innovyze/devops-terraform
😋-bash-⌲ runway --version
2.6.1

devops/tfetest|~/repos/innovyze/devops-terraform
😄-bash-⌲ runway tfenv install 1.0.0
Traceback (most recent call last):
  File "/Users/patrick.raco/.local/bin/runway", line 8, in <module>
    sys.exit(cli())
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/main.py", line 33, in invoke
    return super().invoke(ctx)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/commands/_tfenv/_install.py", line 31, in install
    "terraform path: %s", TFEnvManager().install(version_requested=version)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 348, in install
    if not self.version:
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/backports/cached_property/__init__.py", line 80, in __get__
    val = self.func(instance)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 276, in version
    for i in get_available_tf_versions(include_prerelease_versions)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 118, in get_available_tf_versions
    reverse=True,
  File "/Users/patrick.raco/.pyenv/versions/3.7.12/lib/python3.7/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/patrick.raco/.pyenv/versions/3.7.12/lib/python3.7/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'

devops/tfetest|~/repos/innovyze/devops-terraform
😤-bash-⌲ runway tfenv list
[runway] Terraform versions installed:
0.11.15
0.12.0
0.12.26
0.12.28
0.12.29
0.12.31
0.13.2
0.13.5
0.13.7
0.14.10
0.14.11
0.14.7
0.15.5
1.0.10
1.0.9
1.1.1
1.1.3
1.1.7
1.1.8

devops/tfetest|~/repos/innovyze/devops-terraform
😜-bash-⌲ runway tfenv install 1.1.1

devops/tfetest|~/repos/innovyze/devops-terraform
😀-bash-⌲
```

**Comment by mbordash2** [comment]
We just hit this as well and found two workarounds.
1) in your runway.yaml file, see if you are specifying `terraform_version` in your module `options:` section.  If so, comment that our and let Runway just use a local install.  This will avoid the tf version check that is failing.

2) Edit the `runway/env_mgr/tfenv.py` file and make two changes.
- Line 16: replace the `distutils.version.LooseVersion` with `packaging.version.Version` (`from packaging.version import Version`)
- Line 117: replace `key=LooseVersion` with `key=Version`

**Comment by pataraco** [comment]
@mbordash2 you're 2nd workaround didn't seem to work for me (also using `2.6.1`):

```
😱-bash-⌲ runway --version
2.6.1

😍-bash-⌲ runway tfenv list
[runway] Terraform versions installed:
0.14.7
0.15.5
1.0.10
1.1.8

😛-bash-⌲ runway tfenv uninstall 1.0.10
[runway] uninstalling terraform 1.0.10 from /Users/patrick.raco/.tfenv/versions...
[runway] uninstalled terraform 1.0.10

🙃-bash-⌲ runway tfenv install 1.0.10
[runway] unexpected error encountered when trying to install Terraform
Traceback (most recent call last):
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/commands/_tfenv/_install.py", line 31, in install
    "terraform path: %s", TFEnvManager().install(version_requested=version)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 350, in install
    if not self.version:
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/backports/cached_property/__init__.py", line 80, in __get__
    val = self.func(instance)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 278, in version
    for i in get_available_tf_versions(include_prerelease_versions)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 120, in get_available_tf_versions
    reverse=True,
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/utils/_version.py", line 18, in __init__
    super().__init__(version)
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/packaging/version.py", line 277, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '0.11.15-oci'

😃-bash-⌲ grep -A1 -n LooseVersion /Users/patrick.raco/.local//lib/python3.7/site-packages/runway/env_mgr/tfenv.py
16:# from distutils.version import LooseVersion
17-from distutils.version import Version
--
118:        # key=LooseVersion,
119-        key=Version,
```

**Comment by mbordash2** [comment]
It appears that Terraform is not using a format that is compatible with PEP 440.  So try using the `LegacyVersion` instead which looks to be similar to the distutils' `LooseVersion`.

`from packaging.version import LegacyVersion` and then replace the `key=Version` with `key=LegacyVersion`

More info: https://packaging.pypa.io/en/latest/version.html

```
vscode ➜ /workspaces/create-tf (main ✗) $ poetry run runway tfenv install 1.1.5
[runway] downloading and using Terraform version 1.1.5 ...

vscode ➜ /workspaces/create-tf (main ✗) $ poetry run runway tfenv list
[runway] Terraform versions installed:
1.1.5
vscode ➜ /workspaces/create-tf (main ✗) $ 
```

**Comment by pataraco** [comment]
LOL 

```
😄-bash-⌲ runway tfenv list
Traceback (most recent call last):
  File "/Users/patrick.raco/.local/bin/runway", line 5, in <module>
    from runway._cli.main import cli
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/__init__.py", line 2, in <module>
    from .main import cli
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/main.py", line 11, in <module>
    from . import commands, options
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/commands/__init__.py", line 7, in <module>
    from ._gen_sample import gen_sample
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/commands/_gen_sample/__init__.py", line 20, in <module>
    from ._tf import tf
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/_cli/commands/_gen_sample/_tf.py", line 9, in <module>
    from ....env_mgr.tfenv import get_latest_tf_version
  File "/Users/patrick.raco/.local/lib/python3.7/site-packages/runway/env_mgr/tfenv.py", line 18, in <module>
    from distutils.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'distutils.version' (/Users/patrick.raco/.pyenv/versions/3.7.12/lib/python3.7/distutils/version.py)
```

which version of `python` are we talking about here?
i'm on `3.7.12`

**Comment by GarisonLotus** [comment]
Hey guys, later today we will be reviewing the potential fix and merging afterwords.

**Comment by pataraco** [comment]
@GarisonLotus !
what's up?!
great news - thanks - hope you're doing well!

Could you also, **pretty please**, patch `1.18.3` too?

we're using `runway` for a lot of services and we use a lot of YAML anchors that appear to not be supported any more in the 2.x versions of `runway`. So it would be a lot of effort, i think, to upgrade to 2.x.x.

i took a quick stab at trying to convert the YAML anchors to runway "variables", but failed miserably  ;-) 

e.g.
```
# common settings
air: &assume_iam_role
  assume_role:
    arn: arn:aws:iam::${var aws_account_ids.${env DEPLOY_ENVIRONMENT}}:role/do-cicd
    post_deploy_env_revert: true
cev: &common_env_vars
  cfngin_bucket: ''
  customer: ${var company}
cps: &common_params
  customer: ${var company}
  environment: ${env DEPLOY_ENVIRONMENT}
  company: ${var company}
  region: ${env AWS_REGION}
ctb: &common_terraform_backend_config
  terraform_backend_config:
    bucket: innovyze-${env DEPLOY_ENVIRONMENT}-${env AWS_REGION}-terraform-states
    dynamodb_table: innovyze-${env DEPLOY_ENVIRONMENT}-terraform-locks
    workspace_key_prefix: terraform-state-files  # default: 'env:'
    region: ${env AWS_REGION}
dae: &disable_all_environments  # to be over-written/enabled below
  dev: false
  qa: false
  prod: false
ct: &common_tags
  env: ${env DEPLOY_ENVIRONMENT}
  creator: Onica
  owner: Onica - Pod A
  owner-email: poda@onica.com
  provisioner: terraform
  repo: devops-infrastructure
cp: &common_parameters
  <<: *common_params
  namespace: innovyze-${env DEPLOY_ENVIRONMENT}
  account_id: ${var aws_account_ids.${env DEPLOY_ENVIRONMENT}}
  deployment_iam_role: arn:aws:iam::${var aws_account_ids.${env DEPLOY_ENVIRONMENT}}:role/DevopsCodeBuild
  tags:
    <<: *common_tags

deployments:
  - name: Core Infrastructure (Amazon VPC/Networking/Guardduty)
    modules:
      - path: terraform/configs/networking
        tags: [core, networking]
    module_options:
      <<: *common_terraform_backend_config
      terraform_version:
        "*": 1.1.3      # "*" = all environments or <env> = for a specific one
    environments:
      <<: *disable_all_environments
      dev:
        - us-west-2
      prod: true
    parameters:
      <<: *common_parameters
    regions:
      - us-west-2
      - us-east-1
    account_id: ${var aws_account_ids.${env DEPLOY_ENVIRONMENT}}
    <<: *assume_iam_role
```

**Comment by ITProKyle** [comment]
This is straying from the topic of this issue but @pataraco the issue you are referring to is not that YAML anchors are not supported its that invalid fields are no longer supported in the config file (e.g. `air` if not a valid field in a CFNgin or runway config file). All you need to do is define your anchors under a supported field.

Example:

```yaml
deployments:
  - name: Core Infrastructure (Amazon VPC/Networking/Guardduty)
    modules:
      - path: terraform/configs/networking
        tags: [core, networking]
    module_options: &common_terraform_config
      terraform_version: 1.1.3
      terraform_backend_config:
        bucket: innovyze-${env DEPLOY_ENVIRONMENT}-${env AWS_REGION}-terraform-states
        dynamodb_table: innovyze-${env DEPLOY_ENVIRONMENT}-terraform-locks
        workspace_key_prefix: terraform-state-files  # default: 'env:'
        region: ${env AWS_REGION}
  - modules:
      - ...
    module_options:
      <<: *common_terraform_config
```
