### ISSUE TITLE
[REQUEST] feature

### ISSUE THREAD

**Issue by animaxcg** [onicagroup/runway#154]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when deployment jobs take 2x as long as they need to.

**Describe the solution you'd like**
in the runway.yml (or the driver config). the "- regions:" should have the ability to run in parallel 

**Describe alternatives you've considered**

writting another wrapper around runway (seems very redundant to write a wrapper around a wrapper for a wrapper).

**Comment by ITProKyle** [comment]
> the "- regions:" should have the ability to run in parallel

This functionally already exists.

https://docs.onica.com/projects/runway/en/release/runway_config.html#deployment

> - **regions (List[str])** – AWS region names where modules will be deployed/destroyed. Can optionally define as a map with `parallel` as the key and a list of regions as the value. See **parallel_regions** for more info.
> - **parallel_regions** – Can be defined in place of `regions.parallel[]`. This will cause all modules in the deployment to be executed in all provided regions in parallel (at the same time). Only takes effect when the `CI` environment variable is set, enabling non-interactive mode, as prompts will not be able to be presented. If `CI` is not set, the regions will be processed one at a time. This can be used in tandom with parallel modules. `assume_role.post_deploy_env_revert` will always be `true` when run in parallel.

```yaml
deployments:
  - modules:
      - sampleapp.cfn
    parallel_regions:
      - us-east-1
      - us-west-2
  # or
  - modules:
      - sampleapp.cfn
    regions:
      parallel:
        - us-east-1
        - us-west-2
```
