### ISSUE TITLE
[BUG] terraform_backend_config -> workspace_key_prefix not supported in 2.6.3

### ISSUE THREAD

**Issue by pataraco** [onicagroup/runway#1595]
### Bug Description

@troyready was nice enough to add the capability to define the `workspace_key_prefix` in the `terraform_backend_config` block for versions 1.18.x, e.g.

```
terraform_backend_config:
  bucket: innovyze-${env DEPLOY_ENVIRONMENT}-${env AWS_REGION}-terraform-states
  dynamodb_table: innovyze-${env DEPLOY_ENVIRONMENT}-terraform-locks
  workspace_key_prefix: terraform-state-files  # default: 'env:'        #  <----------- here
  region: ${env AWS_REGION}
```

but seems to have been left out of the 2.X versions of `runway`

```
[dev] 😤-bash-⌲ runway2 plan -e dev --tag s3
[runway] could not find runway.variables.yml or runway.variables.yaml in the current directory; continuing without a variables file
[runway] deploy environment "dev" is explicitly defined in the environment
[runway] if not correct, update the value or unset it to fall back to the name of the current git branch or parent directory
[runway]
[runway]
[runway] Amazon S3:processing deployment (in progress)
[runway] Amazon S3:processing regions sequentially...
[runway] assuming role arn:aws:iam::865412956762:role/DevopsCodeBuild...
[runway] Amazon S3:verified current AWS account matches required account id "865412956762"
[runway]
[runway] Amazon S3.s3:processing module in us-west-2 (in progress)
[runway] 2 validation errors for RunwayTerraformModuleOptionsDataModel
terraform_backend_config -> workspace_key_prefix                     ##  <------------------------ here
  extra fields not permitted (type=value_error.extra)
terraform_version
  str type expected (type=type_error.str)
```

### Expected Behavior

expect to continue to be able to define the `workspace_key_prefix` value in the `terraform_backend_config` block

### Steps To Reproduce

set the setting using version 1.18.3 and perform a test, works fine
upgrade to 2.6.3 and fails

### Runway version

2.6.3

### Installation Type

direct download (curl, wget, etc)

### OS / Environment

[dev] 😬-bash-⌲ uname -a
Darwin racos-mbp.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

feature/96167/runway-2.6.3|~/repos/innovyze/devops-infrastructure
[dev] 😊-bash-⌲ python --version
Python 3.7.12

### Anything else?

thanks for your support!  ;-)
