### ISSUE TITLE
[REQUEST] feature

### ISSUE THREAD

**Issue by animaxcg** [onicagroup/runway#183]
**Is your feature request related to a problem? Please describe.**
I want to be able to have a central directory for my CFNgin configs instead of having them in the module
**Describe the solution you'd like**
in the runway/runway/cfngin.py there should be a class attribute for config_directory that is passed down from runway.yml or runway.variables.yml or as a command line param (probably the form and not the latter 2)

**Describe alternatives you've considered**
each module can point to their own env directory

**Additional context**
It is frustrating when you have multiple modules that share much of the same configuration for stacker runs.

**Comment by animaxcg** [comment]
Yes we use multiple configs in a single module directory that isn't the use case. the use case is modules 1-N use many of the same configs and I would rather manage that in a central place instead of scattered in a dozen module directories and have duplicate entries.

Yaml anchors would work be would still be a pain to manage across a dozen modules but I would rather not have one big runway.yml file but have a runway.yml and dev.yml file for dev etc. keep stacker variables separate from run instruction file

If I have time I'll try to read through the code and create a PR for it and see what you think

**Comment by troyready** [comment]
@animaxcg Can you give an example (e.g. a contrived representation) of the shared configs for which you're looking?

Usually this sort of thing is better solved by putting the more general elements (i.e. the CloudFormation templates) in a shared place (e.g. elsewhere in the same repo, in another repo/archive, etc -- which Runway already supports), but we're definitely open to ideas here.

**Comment by animaxcg** [comment]
These aren't the cloudformation templates these are the stacker env files. in stacker itself you can pass in the config file to use.

in runway you cannot it is hard coded in runway/runway/cfngin.py where your stacker configs live. I can give a better example later

**Comment by animaxcg** [comment]
Submitted a PR probably needs much reviewing as I am not used to your standard. made sure it passed pylint one variable added to 2 classes, you may want to name changed. https://github.com/onicagroup/runway/pull/186

**Comment by ITProKyle** [comment]
Thanks for the PR, it has provided additional insight. There appears to be a conflict in terminology being used both here in the issue and in the PR.

For clarification:

- **CFNgin configuration files:** The files that define what CFNgin does ( instruction files). They contain top-level keys such as `namespace`, `sys_path`, and `stacks`. They are the files where each stack that will be deployed is defined.
- **environment files:** Files containing variable values for a module. How or if these are used depends on the module type. These can empty or even nonexistent. They are one option used to control if a module is deployed for a specific environment/region. Their naming patten is `$DEPLOY_ENVIRONMENT.env` or `$DEPLOY_ENVIRONMENT-$AWS_REGION.env` for CFNgin.

From the PR, it appears you mean environment files instead of configuration files. For passing in shared variables, wither they are global, per-environment, per-region, or any combination of these, using `parameters` in the runway config file is going to be the best option. It can also be used in combination with the environment files which have limitations that `parameters` do not have (e.g. using any data type other than string or bool)

## Parameters Example

This example would meet the requirements you outlined in the PR of a central place to store variable values and not having configuration in the runway config file. You would also be able to dynamically generate the `runway.variables.yml` file to dynamically fill it will values.

### runway.yml

```yaml
deployments:
  - modules:
      - path: sampleapp01.cfn
        environments:
          prod: false
      - path: sampleapp02.cfn
        environment:
          dev: ${var enable_sampleapp02.${env AWS_REGION}}
          prod: false
    parameters:
      namespace: example-${env DEPLOY_ENVIRONMENT}
      nested_variable: ${var ${env DEPLOY_ENVIRONMET}.${env AWS_REGION}.nested_map}
    regions:
      - us-east-1
      - us-west-2
```

### runway.variables.yml

```yaml
dev:
  us-east-1:
    nested_map:
      some_value: us-east-1-value
      a_list:
        - us-east-1-list
  us-west-2:
    nested_map:
      some_value: us-west-2-value
      a_list:
        - us-west-2-list

enable_sampleapp02:
  us-west-2: false
```

### sampleapp01.cfn/config.yml

```yaml
namespace: ${namespace}
cfngin_bucket: ''

sys_path: ./

stacks:
  some_stack:
    class_path: blueprints.app.BlueprintClass
    variables:
      MapValue: ${nested_variable}
```
---

If you don't want to use `parameters`, your next best option would be to store your variables in SSM parameter store for each account and hardcode their paths into lookups in the CFNgin config file. But, keep in mind that these lookups can only be used in specific places so they would need to be used in combination with environment files or `parameters` for things like top-level keys.

This wouldn't provide a _central directory_ but would allow you to populate these values using an external system and SSM would act as a central data store to reference them.

## SSM Example

### sampleapp01.cfn/config.yml

```yaml
namespace: ${namespace}
cfngin_bucket: ''

sys_path: ./

stack:
  some_stack:
    class_path: blueprints.app.BlueprintClass
    variables:
      MapValue: ${ssm /example/nested_variable::load=json, region=us-east-1}
```
---

Another option for a central directory would to be create a single directory for your environment files and symlink the required files into your module directories but this usage was made obsolete with the introduction of `parameters` and lookups in the runway config file.
