### ISSUE TITLE
[BUG] report

### ISSUE THREAD

**Issue by animaxcg** [onicagroup/runway#202]
**Describe the bug**
parallel_regions not kicking off modules in the same deployment in parallel

tested on runway 1.4.0 and 1.4.4

**To Reproduce**
1. clone https://github.com/animaxcg/runway-stacker-test
2. change the bucket to the desired deployment back
3. run start.sh
4. see that it kicks off regions simultaneously but not modules

**Expected behavior**
4. see that it kicks off regions simultaneously and modules

**Comment by ITProKyle** [comment]
I just tested this and it appears to be functioning as correctly.

This runway.yml file:

```yaml
---
# See full syntax at https://docs.onica.com/projects/runway/en/latest/
deployments:
  - modules:
      - module1
      - module2
    parallel_regions:
      - us-west-2
      - us-east-1
```

results in 2 steps.

1. module1 is deployed to us-west-2 and us-east-1 simultaneously.
2. module2 is deployed to us-west-2 and us-east-1 simultaneously after module1 has been deployed to both regions.

If you are looking to deploy all modules to all regions simultaneously, you would need to specify that the modules should be run in parallel as well as the regions.

```yaml
---
# See full syntax at https://docs.onica.com/projects/runway/en/latest/
deployments:
  - modules:
      parallel:
        - module1
        - module2
    parallel_regions:
      - us-west-2
      - us-east-1
```

If this is not what you are looking for, please let me know.
