### ISSUE TITLE
[BUG] serverless module does not respect `environments`

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#266]
**Describe the bug**

Runway version 1.7.3

```yaml
deployments:
  - modules:
      - path: something.sls
        environments:
          example: true
```

Using the above runway.yml example with no environment file in the module directory with a deploy environment of `example`, the module will be skipped even though it is explicitly enabled.

**Expected behavior**

The module should not be skipped.

This should be a quick fix, changing the logic [here](https://github.com/onicagroup/runway/blob/master/runway/module/serverless.py#L181-L184)
