### ISSUE TITLE
[REQUEST] deployments should be able to be run with multiple roles per environment

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#306]
If a common environment encompasses 2+ accounts that need near-identical infrastructure, i should be able to provide a list of roles to use instead of defining multiple deployments for the same environment, only changing the role to use.

Should include an option to run in parallel.

# Example

```yaml
deployments:
  - modules:
      - common-infra.cfn
    regions:
      - us-east-1
    assume-role:
      common:
        - arn:aws:iam:000000000000::some-role
        - arn:aws:iam:111111111111::some-role
        - arn:aws:iam:222222222222::some-role
```

# Concerns

What if there needs to be minor variation in variables per account? (eg. s3 bucket name) How can we account for this? accountId based variable?
