### ISSUE TITLE
[TODO] change publishing to pypi, npm, s3, etc to be trigger on release instead of tag push

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#327]
This will require a separate workflow that is triggered when a release is published on GitHub. The release flow will change to require someone to publish the release from GitHub before anything is published to external sources.

Example workflow

```yaml
name: Publish Release

on:
  release:
    types:
      - published

jobs:
  ...
```

~This works when releases are published from `master`, will need to ensure it will work from the `release` branch.~ Releases are tied to tags so this should not matter.
