### ISSUE TITLE
[REQUEST] deployment/module.environments should be strict

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#333]
As show, this will break legacy uses of `environments`. This would need to be released in a major release or, made toggleable with a default of `false` until the next major release. It should be a top-level config option.

# Example

runway.yml

```yaml
deployments:
  - modules:
      - path: sampleapp.cfn
        parameters:
          key: val
    environments:
      example: 0000/us-east-1
    regions:
      - us-east-1
      - us-west-2
```

## Expectation

- `DEPLOY_ENVIRONMENT=example, accountId=0000, region=us-east-1` deploy the module
- `DEPLOY_ENVIRONMENT=example, accountId=0000, region=us-west-2` always skip the module because the region does not match
- `DEPLOY_ENVIRONMENT=example, accountId=1111, region=us-east-1` always skip the module because the accountId does not match
- `DEPLOY_ENVIRONMENT=prod, accountId=0000, region=us-east-1` always skip the module because the environment is not defined
- `DEPLOY_ENVIRONMENT=prod, accountId=0000, region=us-west-2` always skip the module because the environment is not defined

If `environments` is not defined for an deployment/module, don't skip, let the module class determine if it should skip.

Each environment should still accept an explicit true or false that would enable/disable it for all regions in all accounts.

Each environment should be able to accept an accountId only or a region only.
