### ISSUE TITLE
future state of `environments`

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#343]
In working on #333, there was some brief discussion around how this functionality should be enabled in the config file. This lead to the idea of using something along the lines of `future` to opt-in to using behavior that we intend to make standard in the next major release.

This leaves us room to continue supporting _legacy_ features of `environments` while preparing for the release of Runway v2.0 and allowing users to begin explicitly using the new syntax early.

Here we will outline the syntax and behaviors being removed and those being made standard.

# Usage Being Discontinued in v2.0

Passing values to modules (superseded by `parameters`)

```yaml
environments:
  <env_name>:
    key: val
```

# v2.0

TBD with some behavior described in #333

**Comment by ITProKyle** [comment]
# Proposed Verbose Syntax

It could be easier to parse and read `environments` if we make the definitions more verbose by turning them into objects instead of using a string

```
environments:
  old: <account-id>/<region>  # could also be only <account-id> or <region>
  new:
    - account_id: <account-id>
      region: <region>
  # we can also support the use of alias instead of account id
    - account_alias: <account-alias>
```

This could also remove the need for `account_id` and `account_alias` module options. We could take it one step further and move `assume_role` into the environment definition to tie a role arn or multiple role arns to an environment.

## Other Syntax Options

```yaml
# this would apply to all environment names
# best used when a lookup resolves to this value
environments:
  account_id: <account-id>
  region: <region>
```

We could also move the definitions of environments to the top level or another file and reference them by name on the deployments/modules

```yaml
environments:  # key could be different
  example:
    - account_id: <account-id>
      region: <region>

deployments:
  - environments:  # key could be different
      - example
	modules:
      - sampleapp.cfn
```
