### ISSUE TITLE
[BUG] Module name is not used in serverless modules

### ISSUE THREAD

**Issue by paul-duffy** [onicagroup/runway#356]
When defining a module with a name, the name is never used or displayed back to the user. The expectation is that when listing the modules of a deployment, the module name is used as the option, not the path.

**To Reproduce**
1. Define serverless modules as

```
- path: .
   name: service-a
   type: serverless
- path: .
   name: service-b
   type: serverless
```

2. Run `runway deploy`
3. The following options are shown

```
Configured modules in deployment 'deployment_1':
 1: .
 2: .
```

**Expected behavior**
```
Configured modules in deployment 'deployment_1':
 1: service-a
 2: service-b
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.4

**Additional context**
Full runway config
```
---
deployments:
  - modules:
      - path: .
        name: service-a
        type: serverless
        options:
          args:
            - '--config'
            - sls-a.yml
      - path: .
        name: service-b
        type: serverless
        options:
          args:
            - '--config'
            - sls-b.yml
    environments:
      dev: true 
    regions:
      - us-east-1
```
